// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzsqmbqbfwrskhfotezl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6c3FtYnFiZndyc2toZm90ZXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTgyNTQsImV4cCI6MjA2MjI5NDI1NH0.10eshGs5yIpJmobMM5kdjAH_z-nByricq7zUBIGgS70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);